# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Details

on:
  push:
    branches:  master 

jobs:
  setup-code:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby

      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        bundler-cache: true 
    - name: Run tests
      run: bundle exec rake
      
  build:
     needs: setup-code
     runs-on: ubuntu-latest  
     
     steps:
     - name: login to ghcr.io
       uses: docker/login-action@v1
       with:
          registry: ghcr.io
          username: pungpeee
          password: ${{ secrets.GITHUB_TOKEN }}
      
      
      

