name: Django CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  setup-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
        
  build:
     needs: setup-code
  
     runs-on: ubuntu-latest
     steps:
     
#      - name: Set env
#        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
       
     - uses: actions/checkout@v2
     - name: login to ghcr get image
       uses: docker/login-action@v1
       with:
          registry: ghcr.io
          username: pungpeee
          password: ${{ secrets.GITHUB_TOKEN }}
     
     - name: build images
       uses: docker/build-push-action@v2
       with:
        file: ./src/docker-compose.yml
        tags: ghcr.io/pungpeee/bookinfo
        
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
         - uses: appleboy/scp-action@master
           name: Execute to ssh remote server
           with:
             host: ${{ secrets.HOST }}
             username: pungpeee
             password: ${{ secrets.PASSWORD }}
             run: |
               docker images
               docker ps -a
               
